packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - core-js
  - esbuild
  - sharp

catalog:
  # Dev tooling
  eslint: ^8.57.0
  prettier: ^3.5.3
  typescript: ^5.8.2

  # Misc
  zod: ^3.24.2
  'superjson': 2.2.2
  'sharp': 0.34.0
  'openai': ^4.91.1

  # Tanstack & tRPC
  '@tanstack/react-query': ^5.71.5
  '@trpc/client': ^11.0.2
  '@trpc/react-query': ^11.0.2
  '@trpc/server': ^11.0.2

catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    '@types/react': ^19.0.12
    '@types/react-dom': ^19.0.4
