packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - core-js
  - esbuild
  - sharp

catalog:
  # Dev tooling
  eslint: ^8.57.0
  prettier: ^3.5.3
  tailwindcss: ^3.4.17
  typescript: ^5.8.2

  # Misc
  zod: ^4.1.13
  'superjson': 2.2.2
  'sharp': 0.34.1

  # Tanstack & tRPC
  '@tanstack/react-query': ^5.75.2
  '@trpc/client': ^11.1.2
  '@trpc/react-query': ^11.1.2
  '@trpc/server': ^11.1.2

catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    '@types/react': ^19.0.12
    '@types/react-dom': ^19.0.4
