{
  "packages": [
    "apps/*",
    "packages/*"
  ],
  "onlyBuiltDependencies": [
    "core-js",
    "esbuild",
    "sharp"
  ],
  "catalog": {
    "eslint": "^9.39.2",
    "prettier": "^3.7.4",
    "tailwindcss": "^4.1.18",
    "typescript": "^5.9.3",
    "zod": "^4.3.4",
    "superjson": "2.2.6",
    "sharp": "0.34.5",
    "@tanstack/react-query": "^5.90.16",
    "@trpc/client": "^11.8.1",
    "@trpc/react-query": "^11.8.1",
    "@trpc/server": "^11.8.1"
  },
  "catalogs": {
    "react19": {
      "react": "19.2.3",
      "react-dom": "19.2.3",
      "@types/react": "^19.2.7",
      "@types/react-dom": "^19.2.3"
    }
  }
}