packages:
  - apps/*
  - packages/*

catalog:
  '@tanstack/react-query': ^5.102.8
  '@trpc/client': ^11.18.0
  '@trpc/react-query': ^11.18.0
  '@trpc/server': ^11.18.0
  eslint: ^10.9.1
  prettier: ^3.9.6
  sharp: 0.34.5
  superjson: 2.2.6
  tailwindcss: ^4.3.0
  typescript: ^6.0.3
  zod: ^4.4.3

catalogs:
  react19:
    '@types/react': ^19.2.18
    '@types/react-dom': ^19.2.5
    react: ^19.2.8
    react-dom: ^19.2.8

onlyBuiltDependencies:
  - core-js
  - esbuild
  - sharp
