packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - core-js
  - esbuild
  - sharp

# Only install packages after they've been published for 1+ days
# minimumReleaseAge: 1440

catalog:
  # Dev tooling
  eslint: ^10.4.0
  prettier: ^3.8.3
  tailwindcss: ^4.3.0
  typescript: ^6.0.3

  # Misc
  zod: ^4.4.3
  'superjson': 2.2.6
  'sharp': 0.34.5

  # Tanstack & tRPC
  '@tanstack/react-query': ^5.100.11
  '@trpc/client': ^11.17.0
  '@trpc/react-query': ^11.17.0
  '@trpc/server': ^11.17.0

catalogs:
  react19:
    react: 19.2.6
    react-dom: 19.2.6
    '@types/react': ^19.2.14
    '@types/react-dom': ^19.2.3
