import { exec } from 'child_process';
import { parse } from 'path';
import { mkdirSync, existsSync, writeFileSync, appendFileSync } from 'fs';

const filePath = 'src/generated/git-hash.ts';

function main() {
  exec('git rev-parse --short HEAD', (err, stdout) => {
    if (err) {
      console.error(err);
      process.exit(1);
    }
    const gitHash = stdout.trim();

    const content = ['// DO NOT EDIT THIS FILE. THIS FILE IS AUTO GENERATED.', '', `export const GIT_HASH = '${gitHash}';`, ''];

    const dir = parse(filePath).dir;
    if (!existsSync(dir)) {
      mkdirSync(dir);
    }

    writeFileSync(filePath, content.join('\n'), 'utf-8');
    console.log('Generated file: ', filePath);
  });
}

main();
