name: test

on:
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm ci

  build:
    runs-on: ubuntu-latest
    needs: [setup]
    env:
      NEXT_PUBLIC_BASE_URL: http://localhost:3000
      DATABASE_URL: file:./dev.db
      JWT_SECRET: 1234
      WAKATIME_APP_ID: abc
      WAKATIME_APP_SECRET: abc
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          # Not sure if I should rename this to pnpm?
          cache: 'npm'
      - run: npm ci
      - name: build
        # TODO: inject envs, possibly use https://neon.tech/ for a fast ephemeral env
        run: pnpm build:turbo

  lint:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          # Not sure if I should rename this to pnpm?
          cache: 'npm'
      - run: npm ci
      - name: lint
        run: pnpm lint
